-- insert into table module_name_index
-- manually insert module names from csv to this table
INSERT INTO module_name_index (module_name)
VALUES 
    ("import_acis"),
    ("import_acis_adv"),
    ("import_acis_ct"),
    ("import_catiav4_ct"),
    ("import_acis_cb"),
    ("import_catiav4"),
    ("import_catiav4_adv"),
    ("import_catiav5"),
    ("import_catiav5_adv"),
    ("import_catiav5_ct"),
    ("import_catiav5_cb"),
    ("import_catiav5_apex"),
    ("import_iges"),
    ("import_proe"),
    ("import_proe_ct"),
    ("import_proe_adv"),
    ("import_representation"),
    ("import_sw"),
    ("import_sw_adv"),
    ("import_sw_ct"),
    ("import_ugnx"),
    ("import_ugnx_adv"),
    ("import_ugnx_ct"),
    ("import_step"),
    ("import_step_cb"),
    ("translation_options"),
    ("import_inventor"),
    ("import_inventor_adv"),
    ("import_inventor_APEX"),
    ("import_jt"),
    ("import_sw_ADAMS"),
    ("import_iges_adv"),
    ("import_iges_cb");